# Generated by Django 4.2.23 on 2025-08-17 14:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0004_profiletarget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='completedjob',
            options={'ordering': ['-completed_on']},
        ),
        migrations.AddField(
            model_name='profiletarget',
            name='daily_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='profiletarget',
            name='days_off',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3), default=['Sat', 'Sun'], size=None),
        ),
    ]
