# Generated by Django 4.2.23 on 2025-08-17 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0005_alter_absence_options_alter_completedjob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletarget',
            name='days_off',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3), default=[], size=None),
        ),
    ]
